config/routes.rb
Rails.application.routes.draw do

  root    'races#index', as: 'races_index'

  get     'corridas/:id', to: 'races#info', as: 'races_info'
  post    'races', to: 'races#create', as: 'races_create'

end

app/models/race.rb
class Race < ApplicationRecord

    has_many :laps, dependent: :restrict_with_error 
    
    validates :name, presence: true

    def self.add(laps_hash, pilots_hash)
        
        if laps_hash.empty?
            raise NotAcceptableException.new(I18n.t(:laps_invalid))
        end

        if pilots_hash.empty?
            raise NotAcceptableException.new(I18n.t(:pilots_invalid))
        end

        race = Race.new(
            name: Faker.grandprix
        )

        if !race.save
            raise NotAcceptableException.new(race.errors.full_messages)
        end

        Lap.add_laps(laps_hash, race, Pilot.add_pilots(pilots_hash).map {|item| 
            {
                name: item.name,
                pilot_number: item.pilot_number,
                last_lap: 0,
                id: item.id
            }
        })

        return race
    end

    def self.index
        return Race.select('id, name').order("id desc")
    end

    def self.info(id)
        
        if !id
            NotAcceptableException.new(nil, nil, I18n.t("race_not_found"))
        end

        race = Race.find_by(id: id)

        if !race
            NotAcceptableException.new(nil, nil, I18n.t("race_not_found"))
        end
        
        laps = Lap.where(race_id: race.id).order('lap_number')

        best_lap = nil
        best_lap_time = nil
        best_lap_pilot = nil

        pilots = Pilot
                    .where(
                        "id in (
                            select pilot_id
                            from lap_pilots
                            join laps
                                on lap_pilots.lap_id = laps.id
                            where laps.race_id = ?   
                        )",
                        race.id
                    )
        
        pilot_results = []
        pilot_positions = []
        pilot_positions_dont_finished = []
        laps.each do |lap|

            lap_pilots = LapPilot.includes(:pilot).where(lap_id: lap.id).order(:lap_created_at)

            

            lap_pilots.each_with_index do |lap_pilot, index|

                pilot = pilots.detect {
                    |old_pilot|
                    old_pilot.id == lap_pilot.pilot_id
                }

                if best_lap_time == nil || best_lap_time > lap_pilot.lap_time
                    best_lap = lap.lap_number
                    best_lap_time = lap_pilot.lap_time
                    best_lap_pilot = pilot.full_info
                end

                pilot_result = pilot_results.detect {
                    |old_pilot_result|
                    old_pilot_result[:pilot_number] == pilot.pilot_number
                } 

                if !pilot_result
                    
                    pilot_result = {
                        pilot_number: pilot.pilot_number,
                        name: pilot.name,
                        atual_lap: lap.lap_number,
                        atual_lap_time: lap_pilot.lap_created_at,
                        total_time: Util.new_time(lap_pilot.lap_time),
                        best_lap_number: lap.lap_number,
                        best_lap_time: lap_pilot.lap_time,
                        average_speed: lap_pilot.average_speed
                    }

                    pilot_results.push(pilot_result)

                else

                    pilot_result[:atual_lap] = lap.lap_number
                    pilot_result[:atual_lap_time] = lap_pilot.lap_created_at
                    pilot_result[:total_time] = Util.add_time(pilot_result[:total_time], lap_pilot.lap_time)

                    if lap_pilot.lap_time < pilot_result[:best_lap_time]
                        pilot_result[:best_lap_number] = lap.lap_number
                        pilot_result[:best_lap_time] = lap_pilot.lap_time
                    end

                    pilot_result[:average_speed] = (pilot_result[:average_speed] + lap_pilot.average_speed)/2
                    
                end

                if pilot_result[:atual_lap] == 4 
                    
                    pilot_position = {
                        pilot: pilot,
                        position: pilot_positions.length + 1,
                    }

                    pilot_positions.push(pilot_position)
                end


            end


            pilot_results.each do |pilot_result|

                pilot_position = pilot_positions.detect {
                    |pilot_position|
                    pilot_position[:pilot].pilot_number == pilot_result[:pilot_number]
                }

                if pilot_position
                    pilot_result[:position] = pilot_position[:position]
                end
            end

        end

        pilot_results
                .select{|item| item[:atual_lap] < 4}
                .sort {|a,b|
                comp = (a[:atual_lap_time] <=> b[:atual_lap_time])
                comp.zero? ? (b[:atual_lap] <=> a[:atual_lap]) : comp
                }.each do |item|
                    
                    pilot_position = {
                        pilot: nil,
                        position: pilot_positions.length + 1,
                    }

                    pilot_positions.push(pilot_position)

                    item[:position] = pilot_position[:position]

            end

            pilot_results.each do |item|
                item[:diferente_to_first] = Util.dec_time(pilot_results[0][:total_time], item[:total_time]) if item != pilot_results[0]
            end

            pilot_results.sort! {|a,b| a[:position] <=> b[:position]}

        return {
            best_lap: best_lap,
            best_lap_time: best_lap_time,
            best_lap_pilot: best_lap_pilot,
            pilot_results: pilot_results,
            pilots: pilots,
            name: race.name
        }

    end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController

  def index 
    @data = Race.index
    p "notice" , notice 
  end

  def create
    respond_to do |format|
      begin 
        ActiveRecord::Base.transaction do
          race_params = Parse.race_input_to_hash(params[:file])
          race = Race.add(race_params[:laps], race_params[:pilots])
          format.html { redirect_to races_info_path(race) }
        end
      rescue => e
        p e
        p e.backtrace
        p e.message
        format.html { redirect_to races_index_path, notice: e.message }
      end
    end
  end

  def info
    @data = Race.info(params[:id])
  end

end

app/views/races/index.html.erb
<%= render "layouts/navbar"%>

<% if notice  %>
  <script>
    M.toast({html: '<%= notice %>', classes: 'rounded'});
  </script>
<% end %>

<div class="container">

  <div class="section">
    <h5>Nova corrida</h5>
     <%= form_tag races_create_path, multipart: true do |form| %>
      <div class="row" style="margin-top: 30px;">
        <div class='col s3'>
            <div class="form-group">
                <%= file_field_tag :file %>
            </div>
        </div>
        <div class='col s6'>
        </div>
        <div class='col s3  right-align' style="margin-top: -10px;">
          <%= submit_tag 'Enviar', class:"btn grey"%>
        </div>
      </div>
    <% end %>
  </div>

  
  <div class="divider"></div>

  <% if isnt_empty(@data) %>
  <div class="section">
    <h5>Corridas salvas</h5>
    <table>
        <thead>
          <tr>
              <th><%= t(:name) %></th>
              <th class="right-align"></th>
          </tr>
        </thead>

        <tbody>
        <% @data.each do |item| %>
          <tr>
            <td><%= item.name %></td>
            <td class="right-align"><%= link_to 'Ver resultados', races_info_path(item), class:"btn btn-small grey"%></td>
          </tr>
        <% end %>          
        </tbody>
      </table>
  </div>
  <% end %>


</div>

app/views/races/info.html.erb
<%= render "layouts/navbar"%>


  <div class="row">
    <div class="col s12 m9">
      <div class="card grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= @data[:name] %></span>
          <table>
            <thead>
              <tr>
                  <th class="center-align"><%= t(:position) %></th>
                  <th class="left-align"><%= t(:pilot) %></th>
                  <th class="center-align"><%= t(:laps) %></th>
                  <th class="center-align"><%= t(:total_time) %></th>
                  <th class="center-align"><%= t(:best_lap) %></th>
                  <th class="center-align"><%= t(:avarage_speed) %></th>
                  <th class="center-align"><%= t(:diferente_to_first) %></th>
              </tr>
            </thead>

            <tbody>
            <% @data[:pilot_results].each do |item| %>
              <tr>
                <td class="center-align"><%= item[:position] %>º</td>
                <td class="left-align"><%= item[:pilot_number] %> - <%= item[:name] %></td>
                <td class="center-align"><%= item[:atual_lap] %></td>
                <td class="center-align"><%= mask_time(item[:total_time]) %></td>
                <td class="center-align"><%= item[:best_lap_number] %>º <%= t(:lap) %> - <%= mask_time(item[:best_lap_time]) %></td>
                <td class="center-align"><%= mask_speed(item[:average_speed]) %></td>
                <td class="center-align"><%= mask_time(item[:diferente_to_first]) %> </td>
              </tr>
            <% end %>          
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="col s12 m3">
      <div class="col s12">
        <div class="card grey darken-1">
          <div class="card-content white-text">
            <span class="card-title">Melhor volta</span>
              <%= "#{@data[:best_lap]}º #{t(:lap)} - #{@data[:best_lap_pilot]} - #{mask_time(@data[:best_lap_time])}"%>
          </div>
        </div>
      </div>
      <div class="col s12">
        <div class="card grey darken-1">
          <div class="card-content white-text">
            <span class="card-title">Pilotos</span>
            <table>
              <tbody>
              <% @data[:pilots].each do |item| %>
                <tr>
                  <td class=""><%= item[:pilot_number] %> - <%= item[:name] %></td>
                </tr>
              <% end %>          
              </tbody>
          </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>